services:
  scrutiny:
    image: ghcr.io/analogj/scrutiny:latest-omnibus
    container_name: scrutiny
    restart: unless-stopped
    privileged: true # Required to access drive SMART data
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    devices:
      - /dev/sda:/dev/sda
    volumes:
      - /run/udev:/run/udev:ro
      - ./config:/opt/scrutiny/config
      - ./influxdb:/opt/scrutiny/influxdb
    # ports:
    #   - "8086:8080" # Web UI
    environment:
      - TZ=Europe/Lisbon
      # --- NTFY SETTINGS ---
      - SCRUTINY_NOTIFY_URLS=ntfy://ntfy/jvCi8Kr48Hvx5DKW_my_alerts
    labels:
      - "com.centurylinklabs.watchtower.enable=true" # Only update this container if the label is set
    networks:
      - default_network

networks:
  default_network:
    external: true